Repository Ce11an/surrealdb-openai, pull requests merged in 2024-08, with the labels that each got.

#5 Restructure project
  Makefile
  README.md
  pyproject.toml
  src/surrealdb_openai/app.py
  src/surrealdb_openai/download.py
  src/surrealdb_openai/insert.py
  src/surrealdb_openai/loggers.py
  uv.lock
Labels: documentation, enhancement

#6 Add SurrealDB Python SDK documentation
  README.md
Labels: documentation

#4 Fix threshold filtering and loading of OpenAI token
  .env.example
  README.md
  pyproject.toml
  schema/chats.surql
  src/surrealdb_openai/app.py
  uv.lock
Labels: enhancement

#7 Fix API endpoint names
  src/surrealdb_openai/app.py
  templates/chats.html
  templates/create_chat.html
  templates/index.html
  templates/load_chat.html
  templates/send_system_message.html
  templates/send_user_message.html
Labels: enhancement

#8 Remove redundant `README.md` section
  README.md
Labels: documentation
